### ISSUE TITLE
Small improvements to website

### ISSUE THREAD

**Issue by logankilpatrick** [biaslab/rxinfer-website#12]
Hey folks, a few quick things that should be improved:

- [ ] Move the RxInfer stuff to it's own org on GitHub, makes it clear it's not just a single lab project but an Open Source effort
- [x] add an email to the CoC on who you should make reports too, right now there's no way to make a report
- [x] Make sure there is a discussion section of the website that points to where decisions about the project are being made
- [x] Update the link to the Julia Discourse so that it points to the RxInfer tagged questions or the like, right now it just points to the home page
- [x] Make the website code open source, I don't see where it lives right now but the site looks awesome! 

Thanks!

**Comment by bvdmitri** [comment]
@albertpod @logankilpatrick Shall we merge `site-improvements` branch with all other fixes and move the discussion about separate organisation to a separate issue? Moving all relevant packages and managing a new org is quite some work and will take a lot of time, the changes  in the `site-improvements` could be merged today.

**Comment by bvdmitri** [comment]
Thanks @logankilpatrick ! We will track the issues about new organisation separately.
